# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bluuuuer/Project/Machine_Learning/logistic_regression

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bluuuuer/Project/Machine_Learning/logistic_regression

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bluuuuer/Project/Machine_Learning/logistic_regression/CMakeFiles /home/bluuuuer/Project/Machine_Learning/logistic_regression/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bluuuuer/Project/Machine_Learning/logistic_regression/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LogisticRegression

# Build rule for target.
LogisticRegression: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LogisticRegression
.PHONY : LogisticRegression

# fast build rule for target.
LogisticRegression/fast:
	$(MAKE) -f CMakeFiles/LogisticRegression.dir/build.make CMakeFiles/LogisticRegression.dir/build
.PHONY : LogisticRegression/fast

logistic_regression.o: logistic_regression.cpp.o
.PHONY : logistic_regression.o

# target to build an object file
logistic_regression.cpp.o:
	$(MAKE) -f CMakeFiles/LogisticRegression.dir/build.make CMakeFiles/LogisticRegression.dir/logistic_regression.cpp.o
.PHONY : logistic_regression.cpp.o

logistic_regression.i: logistic_regression.cpp.i
.PHONY : logistic_regression.i

# target to preprocess a source file
logistic_regression.cpp.i:
	$(MAKE) -f CMakeFiles/LogisticRegression.dir/build.make CMakeFiles/LogisticRegression.dir/logistic_regression.cpp.i
.PHONY : logistic_regression.cpp.i

logistic_regression.s: logistic_regression.cpp.s
.PHONY : logistic_regression.s

# target to generate assembly for a file
logistic_regression.cpp.s:
	$(MAKE) -f CMakeFiles/LogisticRegression.dir/build.make CMakeFiles/LogisticRegression.dir/logistic_regression.cpp.s
.PHONY : logistic_regression.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... LogisticRegression"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... logistic_regression.o"
	@echo "... logistic_regression.i"
	@echo "... logistic_regression.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

